language: python
python:
    - 3.3
    - 3.4
    - 3.5

install:
    - pip install -r requirements.txt
    - pip list

script:
    - python manage.py test

branches:
    only:
        - v0.3-devel

