language: python
python:
    - 3.3
    - 3.4
    - 3.5

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install -r requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' || $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry pip install -r requirements.txt; fi

script:
    - python manage.py test

branches:
    only:
        - master

