language: python
python:
    - 3.3
    - 3.4
    - 3.5
    - 3.6

install:
    - travis_retry pip install -r requirements.txt

script:
    - python manage.py migrate
    - python manage.py test

#branches:
#    only:
#        - master

